Feature/sw5 10/26 add meals
aau-giraf/foodplanner pull request #36
Opened 2024-10-30 10:34 UTC by Dra3e

# Description
This adds the pages to add meals to the systems, edit meals in the system, access the camera and add ingredients to the meal. This also includes the models and services to get the information for those pages.

Fixes #26

## Type of change
*Delete unchecked boxes (only for Type of change)*

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?
The code itself has been run using harcoded data and we have written unit-tests.

**Development Configuration**

* Flutter version: 3.24.3
* Dart version: 3.5.3

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas, if necessary
- [ ] I have added tests that prove my fix is effective or that my feature works, if necessary
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-31 10:25 UTC, JacobStokholms commented on foodplanner/lib/services/meal_services.dart
> +      await client.get(Uri.parse('http://127.0.0.1:80/api/Meals/Get/$id'));
I må gerne bruge vores $apiUrl, så vi kan streamline URLl i development og senere til stage,  prod.
Skal opdateres i alle fetches.

Example fra fetch_auth.dart:
 final response = await http.post(Uri.parse('$apiUrl/api/Users/Login'),

2024-11-03 20:51 UTC, Dra3e commented on foodplanner/lib/services/meal_services.dart
> +      await client.get(Uri.parse('http://127.0.0.1:80/api/Meals/Get/$id'));
Jeg har rettet det til at bruge baseUrl fra ApiConfig i stedet, jeg kan godt rette det til præcis det samme som de andre har lavet, men det lader til at gøre det samme, men kræver bare et par flere ændringer.

2024-11-05 11:24 UTC, DollyTheSau requested changes
Follow conventions before pushing

2024-11-05 11:24 UTC, DollyTheSau commented on foodplanner/lib/pages/add_meal_page.dart
> +  static const String routeName = '/add_meal_page'; // Route name for navigation.
Use proper routing, see how its done in routes/index.dart and routes/paths.dart

2024-11-05 11:24 UTC, DollyTheSau commented on foodplanner/lib/pages/add_ingredient_page.dart
> +  static const String routeName = '/add_ingredient_page'; // Route name for navigation.
Same as meal page, route it the proper way through index and paths

2024-11-14 12:36 UTC, lundholm73 commented
I skal resolve conflicts før vi kigger på den

2024-11-15 08:12 UTC, lundholm73 commented on foodplanner/lib/services/food_image_service.dart
> +/// This method is used to send the inputted image to the back-end.
Slet hvis det ikke skal brugs

2024-11-15 08:12 UTC, lundholm73 commented on foodplanner/pubspec.yaml
> +    openapi_generator: ^5.0.2
hvorfor går vi ned i version?

2024-11-15 08:12 UTC, lundholm73 commented on foodplanner/test/page_tests/add_ingredient_page_test.mocks.dart
> +// ignore_for_file: type=lint
Væk med det right?

2024-11-15 08:12 UTC, lundholm73 commented on foodplanner/lib/config/colors.dart
Hvorfor har i været inde og ændre farverne?

2024-11-15 09:26 UTC, lundholm73 commented on foodplanner/lib/config/colors.dart
i må lige kigge i filen var lidt dårlig til og kopiere

2024-11-18 10:34 UTC, Dra3e commented on foodplanner/test/page_tests/add_ingredient_page_test.mocks.dart
> +// ignore_for_file: type=lint
Det er auto-generated mocks filer, så det giver ikke meget mening at fjerne det, da det vil komme tilbage næste gang vi auto-generate

2024-11-20 07:42 UTC, JacobStokholms approved these changes

2024-11-20 07:43 UTC, DollyTheSau approved these changes

2024-11-20 08:15 UTC, merged